### ISSUE TITLE
Error while formatting C++ code with clang-format.exe integrated in the extension (Windows 10)

### ISSUE THREAD

**Issue by andywowws** [microsoft/vscode-cpptools#12289]
### Environment

- OS and Version: Win10
- VS Code Version: 1.89.0
- C/C++ Extension Version: 1.20.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:Have an error while formatting:
Formatting failed:
c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-1.20.5-win32-x64/bin/../LLVM/bin/clang-format.exe -style=file -fallback-style=google -sort-includes=0 --Wno-error=unknown -assume-filename=D:\lgtm\P3612.cpp D:\LGTM\P3612.CPP

Steps to reproduce:
1. Press "Shift+Alt+F"
2. See error

Expected behavior:
No such error just as version 1.19.9 of the extension  
.clang-format  
```yaml
---
# 语言: None, Cpp, Java, JavaScript, ObjC, Proto, TableGen, TextProto
Language: Cpp
# 基于某一主题上的修改
BasedOnStyle: Google
# 缩进宽度
IndentWidth: 4
# 缩进case标签
IndentCaseLabels: true
# 访问说明符(public、private等)的偏移
AccessModifierOffset: -4
# 括号之前不断行
BreakBeforeBraces: Attach
#
AllowShortIfStatementsOnASingleLine: false
#
AllowShortLoopsOnASingleLine: false
```

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "D:/mingw64/bin/g++.exe",
            "cStandard": "c17",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}

log
Formatting failed:
c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-1.20.5-win32-x64/bin/../LLVM/bin/clang-format.exe -style=file -fallback-style=google -sort-includes=0 --Wno-error=unknown -assume-filename=D:\lgtm\P3612.cpp D:\LGTM\P3612.CPP
```
