### ISSUE TITLE
.clang-format file ignored

### ISSUE THREAD

**Issue by CodeMouse92** [microsoft/vscode-cpptools#1519]
* Ubuntu 17.10
* Visual Studio Code 1.19.3
* C/C++ extension 0.14.6
* `clang-format-5.0`
* Same problem with or without 'Clang-Format' extension

There are a few complaints about this, but the difference here is **I have validated** the `.clang-format` file is syntactically correct via `clang-format-5.0 -dump-config`, and also run it through a YAML linter.

No matter what settings I select, `Format Document` always falls back on some preset standard. 

From user settings:

```json
  "C_Cpp.clang_format_fallbackStyle": "none",
  "C_Cpp.clang_format_path": "/usr/bin/clang-format-5.0",
```

All others are default. I confirmed that `/usr/bin/clang-format-5.0' is the correct path, and that `.clang-format` exists in the base project directory.

clang-format works just fine when run *either* of the following commands are run in the terminal:

```bash
$ cd pawlib-source/include/pawlib; clang-format-5.0 flex_array.hpp
$ clang-format-5.0 pawlib-source/include/pawlib/flex_array.hpp
```

I turned on "Information" level logging for this extension, but it displayed nothing related to this issue.

Yet, after all of this, running `Format Document` still uses an unknown fallback.

**Comment by sean-mcmanus** [comment]
`clang_format_path` needs to be the full path, including the name of the binary. Does it work after adding the file name? We should probably just add the expected name if the path ends in a directory.

**Comment by CodeMouse92** [comment]
@sean-mcmanus, that literally *is* the full path (on Unix systems anyhow). Remember, on Unix, binary files often do not have file extensions.

That path *is* a symbolic link to `/usr/lib/llvm-5.0/bin/clang-format`, which shouldn't make a difference; and it doesn't. Specifying that as the full path instead still does NOT fix the problem.

**Comment by sean-mcmanus** [comment]
Can you set the C_Cpp.loggingLevel to the hidden value of 6 and then do the format operation? That should enable debug logging for formatting. You don't need to post your code, but can you look for what stage of formatting appears to fail? Be sure to remove that loggingLevel value later, because it makes stuff slower.

**Comment by CodeMouse92** [comment]
No stage reports failure. In fact, it reports success. It *does* change the file, as I mentioned, but it isn't using my `.clang-format` file, which is located in the root of the workspace folder.

**Comment by sean-mcmanus** [comment]
Can you provide the .clang-format file you use?

**Comment by CodeMouse92** [comment]
Absolutely. Once again, it passes both YAML linting and `clang-format-5.0 -dump-config`.

```yaml
---
Language:        Cpp
BasedOnStyle:  LLVM

AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands:   true
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: false
BinPackArguments: true
BinPackParameters: true
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Allman
BreakBeforeInheritanceComma: false
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakConstructorInitializers: BeforeColon
BreakStringLiterals: true
ColumnLimit:     80
CommentPragmas:  '^ IWYU pragma:'
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat:   false
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
ForEachMacros:
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
IncludeCategories:
  - Regex:           '^(<|"(anari|pawlib|ratscript|simplexpress|stormsound|trailcrest)/)'
    Priority:        4
  - Regex:           '^(<|"(cpgf|cinder|eigen|opus|pugixml)/)'
    Priority:        3
  - Regex:           '^".*'
    Priority:        2
  - Regex:           '^<.*'
    Priority:        1
IncludeIsMainRegex: '(_tests)?$'
IndentCaseLabels: true
IndentWidth:     4
IndentWrappedFunctionNames: true
KeepEmptyLinesAtTheStartOfBlocks: false
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
PenaltyBreakAssignment: 2
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyExcessCharacter: 1000000
PenaltyReturnTypeOnItsOwnLine: 60
PointerAlignment: Left
ReflowComments:  true
SortIncludes:    true
SortUsingDeclarations: true
SpaceAfterCStyleCast: false
SpaceAfterTemplateKeyword: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles:  false
SpacesInContainerLiterals: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard:        Cpp11
TabWidth:        4
UseTab:          Never
```
