### ISSUE TITLE
Possibility for preventing including compiler specific headers from system folders.

### ISSUE THREAD

**Issue by misaz** [microsoft/vscode-cpptools#7531]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Debian 10
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I try to develop Linux Kernel using Visual Studio Code. I need to prevent automaticaly including compiloer specific folders for code completion purposes. For example file `errno.h`. This file is presented in project (in my case it is `/home/michal/linux/include/linux/errno.h`), but Visual Stduio Code for some reason uses file from system directory (`/usr/include/asm-generic/errno.h`) rather. These files are not the same. Linux code defines more structures, functions, and so on in their header files. According to https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference system libraries should be automaticaly included only when compilerPath is specified. So, I tiried follwoing `.vscode/c_cpp_properties.json` configuration without this property:

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
        }
    ],
    "version": 4
}
```
then I ran `C/C++: Reset IntelliSense Database` command but this does not helped. Log diagnostic still shows that system folders (`/usr/lib/gcc/x86_64-linux-gnu/8/include`, `/usr/local/include`, `/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed`, `/usr/include/x86_64-linux-gnu` and  `/usr/include`) are included.

```
-------- Diagnostics - 16. 5. 2021 21:43:23
Version: 1.3.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "macFrameworkPath": [],
    "compilerArgs": [],
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": false,
    "compilerPath": "/usr/bin/gcc",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/michal/linux/drivers/bluetooth/bpa10x.c ]:
    /home/michal/linux/drivers/bluetooth/bpa10x.c
Translation Unit Configurations:
[ /home/michal/linux/drivers/bluetooth/bpa10x.c ]:
    Process ID: 3983
    Memory Usage: 95 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/8/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /home/michal/linux/include
        /home/michal/linux/arch/x86/include
        /home/michal/linux/arch/arm/include/generated
        /home/michal/linux/arch/mips/include
        /home/michal/linux/arch/ia64/include
        /home/michal/linux/arch/s390/include
        /home/michal/linux/arch/ia64/include/uapi
        /home/michal/linux/include/uapi
        /home/michal/linux/arch/parisc/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=80300
Total Memory Usage: 95 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 105625

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: /home/michal/linux/include/asm-generic/barrier.h
    Alternative: "/home/michal/linux/tools/include"
Using: /usr/include/asm-generic/bitsperlong.h
    Alternative: "/home/michal/linux/tools/include/uapi"
    Alternative: "/home/michal/linux/include/uapi"
    Alternative: "/home/michal/linux/include"
Using: /home/michal/linux/arch/x86/include/asm/alternative-asm.h
    Alternative: "/home/michal/linux/arch/s390/include"
Using: /home/michal/linux/arch/x86/include/asm/alternative.h
    Alternative: "/home/michal/linux/arch/parisc/include"
    Alternative: "/home/michal/linux/arch/arm64/include"
Using: /home/michal/linux/arch/x86/include/asm/arch_hweight.h
    Alternative: "/home/michal/linux/arch/x86/um"
    Alternative: "/home/michal/linux/arch/mips/include"
Using: /home/michal/linux/arch/x86/include/asm/asm-offsets.h
    Alternative: "/home/michal/linux/tools/perf/util/include"
    Alternative: "/home/michal/linux/arch/xtensa/include"
    Alternative: "/home/michal/linux/arch/sparc/include"
    Alternative: "/home/michal/linux/arch/sh/include"
    Alternative: "/home/michal/linux/arch/riscv/include"
    Alternative: "/home/michal/linux/arch/powerpc/include"
    Alternative: "/home/michal/linux/arch/openrisc/include"
    Alternative: "/home/michal/linux/arch/nios2/include"
    Alternative: "/home/michal/linux/arch/microblaze/include"
    Alternative: "/home/michal/linux/arch/m68k/include"
    Alternative: "/home/michal/linux/arch/ia64/include"
    Alternative: "/home/michal/linux/arch/hexagon/include"
    Alternative: "/home/michal/linux/arch/c6x/include"
    Alternative: "/home/michal/linux/arch/arm/include"
    Alternative: "/home/michal/linux/arch/arc/include"
    Alternative: "/home/michal/linux/arch/alpha/include"
Using: /home/michal/linux/arch/x86/include/asm/atomic.h
    Alternative: "/home/michal/linux/tools/arch/x86/include"
    Alternative: "/home/michal/linux/arch/h8300/include"
    Alternative: "/home/michal/linux/arch/csky/include"
Using: /usr/include/x86_64-linux-gnu/asm/auxvec.h
    Alternative: "/home/michal/linux/arch/xtensa/include/uapi"
    Alternative: "/home/michal/linux/arch/x86/include/uapi"
    Alternative: "/home/michal/linux/arch/sparc/include/uapi"
    Alternative: "/home/michal/linux/arch/sh/include/uapi"
    Alternative: "/home/michal/linux/arch/s390/include/uapi"
    Alternative: "/home/michal/linux/arch/riscv/include/uapi"
    Alternative: "/home/michal/linux/arch/powerpc/include/uapi"
    Alternative: "/home/michal/linux/arch/nds32/include/uapi"
    Alternative: "/home/michal/linux/arch/mips/include/uapi"
    Alternative: "/home/michal/linux/arch/microblaze/include/uapi"
    Alternative: "/home/michal/linux/arch/ia64/include/uapi"
    Alternative: "/home/michal/linux/arch/arm64/include/uapi"
    Alternative: "/home/michal/linux/arch/arm/include/uapi"
    Alternative: "/home/michal/linux/arch/alpha/include/uapi"
Using: /home/michal/linux/arch/x86/include/asm/barrier.h
    Alternative: "/home/michal/linux/tools/virtio"
    Alternative: "/home/michal/linux/tools/arch/xtensa/include"
    Alternative: "/home/michal/linux/tools/arch/sparc/include"
    Alternative: "/home/michal/linux/tools/arch/sh/include"
    Alternative: "/home/michal/linux/tools/arch/s390/include"
    Alternative: "/home/michal/linux/tools/arch/powerpc/include"
    Alternative: "/home/michal/linux/tools/arch/mips/include"
    Alternative: "/home/michal/linux/tools/arch/ia64/include"
    Alternative: "/home/michal/linux/tools/arch/arm64/include"
    Alternative: "/home/michal/linux/tools/arch/arm/include"
    Alternative: "/home/michal/linux/tools/arch/alpha/include"
    Alternative: "/home/michal/linux/arch/nds32/include"
Using: /usr/include/x86_64-linux-gnu/asm/bitsperlong.h
    Alternative: "/home/michal/linux/tools/arch/x86/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/sparc/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/s390/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/riscv/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/powerpc/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/parisc/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/mips/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/microblaze/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/ia64/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/hexagon/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/h8300/include"
    Alternative: "/home/michal/linux/tools/arch/arm64/include/uapi"
    Alternative: "/home/michal/linux/tools/arch/alpha/include/uapi"
    Alternative: "/home/michal/linux/arch/parisc/include/uapi"
    Alternative: "/home/michal/linux/arch/arm/include/generated/uapi"
Using: /usr/include/x86_64-linux-gnu/asm/byteorder.h
    Alternative: "/home/michal/linux/arch/openrisc/include/uapi"
    Alternative: "/home/michal/linux/arch/nios2/include/uapi"
    Alternative: "/home/michal/linux/arch/m68k/include/uapi"
    Alternative: "/home/michal/linux/arch/hexagon/include/uapi"
    Alternative: "/home/michal/linux/arch/h8300/include/uapi"
    Alternative: "/home/michal/linux/arch/csky/include/uapi"
    Alternative: "/home/michal/linux/arch/c6x/include/uapi"
    Alternative: "/home/michal/linux/arch/arc/include/uapi"
Using: /home/michal/linux/arch/x86/include/asm/cache.h
    Alternative: "/home/michal/linux/tools/testing/selftests/powerpc/stringloops"
    Alternative: "/home/michal/linux/arch/um/include"
Using: /home/michal/linux/arch/x86/include/asm/current.h
    Alternative: "/home/michal/linux/arch/arm/include/generated"
Using: /usr/include/x86_64-linux-gnu/asm/ist.h
    Alternative: "/home/michal/linux/arch/x86/include"
Using: /home/michal/linux/arch/x86/include/asm/kasan.h
    Alternative: "/home/michal/linux/tools/testing/selftests/powerpc/copyloops"
Using: /home/michal/linux/arch/x86/include/asm/processor.h
    Alternative: "/home/michal/linux/tools/testing/selftests/powerpc/primitives"
Using: /usr/include/endian.h
    Alternative: "/home/michal/linux/tools/include/tools"
    Alternative: "/home/michal/linux/include/config/usb/ohci/little"
    Alternative: "/home/michal/linux/fs/ntfs"
    Alternative: "/home/michal/linux/fs/befs"
Using: /usr/include/features.h
    Alternative: "/home/michal/linux/kernel/sched"
    Alternative: "/home/michal/linux/include/xen"
    Alternative: "/home/michal/linux/include/xen/interface"
    Alternative: "/home/michal/linux/drivers/md/bcache"
Using: /home/michal/linux/include/generated/autoconf.h
    Alternative: "/home/michal/linux/tools/testing/radix-tree"
Using: /usr/include/x86_64-linux-gnu/gnu/stubs.h
    Alternative: "/home/michal/linux/tools/testing/selftests/bpf"
Using: /home/michal/linux/include/linux/bug.h
    Alternative: "/home/michal/linux/tools/bootconfig/include"
Using: /home/michal/linux/include/linux/delay.h
    Alternative: "/home/michal/linux/tools/testing/selftests/rcutorture/formal/srcu-cbmc/empty_includes"
Using: /home/michal/linux/include/linux/kconfig.h
    Alternative: "/home/michal/linux/tools/testing/selftests/rcutorture/formal/srcu-cbmc/include"
Using: /home/michal/linux/include/linux/mm.h
    Alternative: "/home/michal/linux/tools/testing/scatterlist"
Using: /usr/include/linux/socket.h
    Alternative: "/home/michal/linux/tools/perf/trace/beauty/include"
    Alternative: "/home/michal/linux/tools/perf/include/bpf"
Using: /usr/include/linux/types.h
    Alternative: "/home/michal/linux/tools/testing/selftests/rcutorture/formal/srcu-cbmc/empty_includes/uapi"
Using: /usr/lib/gcc/x86_64-linux-gnu/8/include/stddef.h
    Alternative: "/home/michal/linux/include/uapi/linux"
    Alternative: "/home/michal/linux/include/linux"
Using: /usr/include/string.h
    Alternative: "/home/michal/linux/tools/include/linux"
    Alternative: "/home/michal/linux/tools/bootconfig/include/linux"
    Alternative: "/home/michal/linux/include/config/netfilter/xt/match"
    Alternative: "/home/michal/linux/include/asm-generic"
    Alternative: "/home/michal/linux/arch/xtensa/include/asm"
    Alternative: "/home/michal/linux/arch/x86/include/asm"
    Alternative: "/home/michal/linux/arch/x86/boot"
    Alternative: "/home/michal/linux/arch/sparc/include/asm"
    Alternative: "/home/michal/linux/arch/sh/include/asm"
    Alternative: "/home/michal/linux/arch/s390/include/asm"
    Alternative: "/home/michal/linux/arch/riscv/include/asm"
    Alternative: "/home/michal/linux/arch/powerpc/include/asm"
    Alternative: "/home/michal/linux/arch/powerpc/boot"
    Alternative: "/home/michal/linux/arch/parisc/include/asm"
    Alternative: "/home/michal/linux/arch/openrisc/include/asm"
    Alternative: "/home/michal/linux/arch/nios2/include/asm"
    Alternative: "/home/michal/linux/arch/nds32/include/asm"
    Alternative: "/home/michal/linux/arch/mips/include/asm"
    Alternative: "/home/michal/linux/arch/microblaze/include/asm"
    Alternative: "/home/michal/linux/arch/m68k/include/asm"
    Alternative: "/home/michal/linux/arch/ia64/include/asm"
    Alternative: "/home/michal/linux/arch/hexagon/include/asm"
    Alternative: "/home/michal/linux/arch/h8300/include/asm"
    Alternative: "/home/michal/linux/arch/csky/include/asm"
    Alternative: "/home/michal/linux/arch/csky/abiv2/inc/abi"
    Alternative: "/home/michal/linux/arch/csky/abiv1/inc/abi"
    Alternative: "/home/michal/linux/arch/c6x/include/asm"
    Alternative: "/home/michal/linux/arch/arm64/include/asm"
    Alternative: "/home/michal/linux/arch/arm/include/asm"
    Alternative: "/home/michal/linux/arch/arc/include/asm"
    Alternative: "/home/michal/linux/arch/alpha/include/asm"
```

I also tried to specify compilerPath to `/bin/true` (and then run `C/C++: Reset IntelliSense Database` command), but vscode still loaded system folders of GCC. Finally I also tried reconfigure `C_Cpp.default.systemIncludePath` property in `settings.json` to following content (ant then run `C/C++: Reset IntelliSense Database` command) but this also did not help.

```
{
    "remote.SSH.remotePlatform": {
        "192.168.0.41": "linux"
    },
    "files.exclude": {
        "**/.*.cmd": true,
        "**/*.d": true,
        "**/*.dtbo": true,
        "**/*.ko": true,
        "**/*.mod": true,
        "**/*.mod.c": true,
        "**/*.o": true,
        "**/*.tmp": true
    },
    "editor.tabSize": 8,
    "C_Cpp.default.systemIncludePath": [
    ],
}
```

How to prevent vscode to include headers from system folders?
